require 'variation/version'

require 'variation/errors'
require 'variation/range'
require 'variation/functions/constant_function'
require 'variation/functions/linear_function'
require 'variation/functions/sigmoid_function'
require 'variation/change'
require 'variation/changes/immediate_change'
require 'variation/changes/linear_change'
require 'variation/changes/sigmoid_change'
require 'variation/profile'
